pref("extensions.pastetotab@loucypher.description", "chrome://pastetotab/locale/pasteToTab.properties");
pref("extensions.pastetotab.debug", false);
pref("extensions.pastetotab.firstRun", true);
pref("extensions.pastetotab.contributionURL", "https://addons.mozilla.org/%LOCALE%/%APP%/addon/paste-to-tab-and-go/contribute/installed/");
pref("extensions.pastetotab.urlbar.pasteToNewTabAndGo", true);
pref("extensions.pastetotab.urlbar.pasteTextAndGo", true);
pref("extensions.pastetotab.tab.pasteToThisTabAndGo", true);
pref("extensions.pastetotab.tabbar.pasteToNewTabAndGo", true);
pref("extensions.pastetotab.searchbar.pasteToNewTabAndSearch", true);
